### ISSUE TITLE
Cannot modify ExpRatio column in Experience.txt

### ISSUE THREAD

**Issue by DanilaSpevak** [olegbl/d2rmm#1]
Attached is a simple test mod to alter ExpRatio column in Experience.txt.

In the result the column remains unchanged. With any other column name the values change correctly.

[LowerXPPenalty.zip](https://github.com/olegbl/d2rmm/files/8494993/LowerXPPenalty.zip)

**Comment by olegbl** [comment]
The last column in Blizzard's .txt files ends with "\r" since they use Windows style line endings. D2RMM does not strip these out when parsing (...though maybe it should). You can work around this by doing:
```
row['ExpRatio\r'] = 1024;
```
