### ISSUE TITLE
d2rmm on linux

### ISSUE THREAD

**Issue by kalohr** [olegbl/d2rmm#11]
hello !

very glad for this mod manager !

is it by any chance possible to run on linux ? 

regards, 

Michael

**Comment by olegbl** [comment]
Some users have reported that they're able to run it via Lutris. I have no personal experience.

Here's what I wrote last time about this topic:

> It's an Electron app, so theoretically, it can be built for Windows, OSX and Linux. I have not set up the build process for anything but Windows, however. The most likely challenge you'd run into is that D2RMM uses CascLib.dll (http://www.zezula.net/en/casc/casclib.html) and comes with the Windows version of that library. You'd probably have to download the Linux version and replace the dll packaged in /tools/ with it.

I don't currently have any plans for a Linux or OSX release myself, but would be happy to accept PRs for it (or, feel free to just fork.)

**Comment by kalohr** [comment]
may send some errors here, as I have never used electricity or javascript before for desktop apps?
