### ISSUE TITLE
Add flag to mod description to determine that this mod is safe for battle.net online and changes only local string values

### ISSUE THREAD

**Issue by AlexSnowLeo** [olegbl/d2rmm#13]
For example [NumberedRuneNames](https://github.com/olegbl/d2rmm.mods/tree/main/NumberedRuneNames) is safe for run players on the battle.net realms. 
But [HoradricForging](https://github.com/olegbl/d2rmm.mods/tree/main/HoradricForging) is not.
And [StackableRunes](https://github.com/olegbl/d2rmm.mods/tree/main/StackableRunes) is safe partly (only runes skin is changed, but stack feature is not works on battle.net realm).

**Comment by olegbl** [comment]
Sorry, I'm not going to get into the business of supporting mods for online use. People can do so entirely at their own risk.
