### ISSUE TITLE
Subsection feature

### ISSUE THREAD

**Issue by alex-c-i** [olegbl/d2rmm#14]
Hello,

I implemented a pseudo loot filter that allows removing all item bases individually in D2R and organized them by TC as this is how the game does it internally but people and I quickly realised its not that good of a structure. I will reimplement it as: 
- weapons: swords, scepters, etc
- armors: head, body, etc
But it would be very helpfull to be able to have subsections for items quality: normal, exceptional and elite items.

Is this something you will consider adding support for in D2RMM ?

PS: as  a bonus an enable / disable all toggle for each section / subsection would also be very helpfull.

Thanks,
Alex.

**Comment by olegbl** [comment]
Yup, that seems reasonable. In fact, I think UX options for mod settings need to be expanded quite a bit as more complex mods are being developed. I just don't have any time to do so right now.

**Comment by alex-c-i** [comment]
D2RMM itself is a bit too complex for me at the moment so no promises for now as to whether I can figure out how to implement these features myself but I will try to have a deeper look into it over the weekend.

**Comment by Caedendi** [comment]
I second these 2 requests, thanks for considering them.
