### ISSUE TITLE
[TypeScript] loading imports from a subfolder is broken

### ISSUE THREAD

**Issue by Caedendi** [olegbl/d2rmm#20]
D2RMM 1.6.1.

**Expected behaviour:** loading imports uses the current file's path
**Actual behaviour:** loading imports always looks at the mod folder path, even when the current file that is loading an import is in a subfolder.

**Example:**
Say I have the following file/folder structure:

```
/mymod/mod.json
/mymod/mod.ts
/mymod/sub/file1.ts
/mymod/sub/file2.ts
/mymod/sub/file3.ts
```

- `mod.ts` imports only `file1.ts`
- `file1.ts` imports `file2.ts` and `file3.ts`

mod.ts:
```
import { file1 } from "./sub/file1"; // works fine
```

file1.ts:
```
import { file2 } from "./sub/file2"; // VSCode says error, D2RMM works
import { file3 } from "./file3";     // VSCode says fine, D2RMM throws error
```

Error: _Mod mymod  encountered a compile error! Error: BridgeAPI.readModCode: Failed to read mods\mymod\file3.ts_

**Comment by olegbl** [comment]
Thanks for the report! I'll patch this real quick while no existing TS D2RMM mods rely on the current behavior yet.
