### ISSUE TITLE
[TypeScript] how to load D2RMM as a library?

### ISSUE THREAD

**Issue by Caedendi** [olegbl/d2rmm#21]
Is there a way to load D2RMM as a library for a TypeScript-style mod and remove all the errors my IDE gives? 

Same question for config/mod.json. Would be great if there was some way for the IDE to recognize mod.json as `config`, if settings exist and if types match.

**Comment by olegbl** [comment]
If you author the TS code inside D2RMM/mods, TSC should pick up all the types automatically from types.d.ts.

I'm not aware of anything that does type checking for JSON files.

**Comment by Caedendi** [comment]
How do I do that? I'm a complete TS noob

**Comment by olegbl** [comment]
You should be able to copy/paste the `types.d.ts` file from the D2RMM folder to any other folder of your choosing and get type checking and auto completion.
