### ISSUE TITLE
Auto-update not working

### ISSUE THREAD

**Issue by Caedendi** [olegbl/d2rmm#24]
I have multiple folders for D2RMM. For both my 1.7.0 folders auto-update doesn't work:
- it shows the message that an update is available
- I press update
- it downloads, extracts and runs
- a black command window pops up and disappears (one time I saw some red letters for a few ms but can't make a screenshot)
- no update has been applied

Both of them run as administrator.

**Comment by olegbl** [comment]
Could you post the log (d2rmm.log) please?

I'm guessing that the PowerShell script that's meant to copy over the new files into D2RMM directory is failing (that's the "black command window").

If you don't mind, what would really help would be:
1. Open up PowerShell.
2. Navigate to `%temp%\d2rmm\updater\` (assuming PowerShell opens in your user directory, type in `cd AppData\Local\Temp\D2RMM\Updater` and hit enter).
3. Type in "./update.ps1" and hit enter.

This should run the updater and start D2RMM. If it has any errors, they should show up here.

**Comment by Caedendi** [comment]
Apologies for the lack of updates, I haven't gotten around to it yet but I will get back to you.

**Comment by olegbl** [comment]
No worries. There's no rush.

**Comment by olegbl** [comment]
I don't have a repro, but hopefully https://github.com/olegbl/d2rmm/commit/e5c7aef12cea8bf14a09758e141d31d73eb68452 helps.
