### ISSUE TITLE
[feature request] Add hook to "Run D2R"

### ISSUE THREAD

**Issue by Chrikomu** [olegbl/d2rmm#25]
I am experimenting with a grail tracker mod. One way to implement it, would be the read the save files before each launch, and update some GUI accordingly. Currently this is only possible by remembering to also press "Install Mods" before each launch.

**Comment by olegbl** [comment]
Cool mod idea!

**Comment by olegbl** [comment]
Closed by https://github.com/olegbl/d2rmm/commit/5c21e79e9a57ddb908c08b8057d2f1fda5802a2c
