### ISSUE TITLE
Multiple launch profiles

### ISSUE THREAD

**Issue by IhanaMies** [olegbl/d2rmm#28]
I have several seeds for different purposes and regularly switch between them.
It would be nice to save them and launch without opening the settings and editing the launch parameters.

**Comment by olegbl** [comment]
For different mod configs, the recommendation is to have multiple D2RMM installations (i.e. in multiple folders).

For different D2R launch configs, the recommendation is to use normal shortcuts to D2R.exe instead of using D2RMM as a launcher.
