### ISSUE TITLE
arm64 build

### ISSUE THREAD

**Issue by paul-khudan** [olegbl/d2rmm#32]
Hi there!
Trying to build this under arm64 on macos. Having problems with `yarn install`, but I might assume there are more dependencies that may cause troubles.
Could you share any thoughts on preparing a build for arm64?

**Comment by olegbl** [comment]
Sorry, I do not have anything to suggest.

Do note you'd also have to build CascLib for arm64. I think ffi-napi has MacOS support, so it should be possible to still call into the lib, though I don't know if the file format changes from a .dll to something else.

**Comment by paul-khudan** [comment]
Thanks for the reply.
