### ISSUE TITLE
Object.keys() doesn't work?

### ISSUE THREAD

**Issue by andrecastelo** [olegbl/d2rmm#5]
Hey man, love the work with D2RMM. I'm playing around with a mod, trying to refactor some code, and while trying to use `Object.keys(...)` I get this:

![image](https://user-images.githubusercontent.com/726360/221329021-eacbc4dc-f3ce-4ef9-961f-d80c98c70547.png)

Is this a limitation on electron or on the way that the mod code is executed?

**Comment by olegbl** [comment]
See "Mod API" section in https://www.nexusmods.com/diablo2resurrected/mods/169

> Note: The JavaScript inside this file is run without access to the global scope. (e.g. You’ll need to use for/in instead of Object.keys since Object is not available). The Math API is exposed for you, however.

**Comment by andrecastelo** [comment]
Thanks for the clarification!
