### ISSUE TITLE
Feature Request: regions/tabs in mod settings

### ISSUE THREAD

**Issue by Caedendi** [olegbl/d2rmm#8]
Hi, [my extended loot filter](https://github.com/Caedendi/D2RMM-Loot-Filter-Extended) has grown to have quite the number of settings for users to play with. For readability, I think my users would really like it if the settings could be divided into either regions or tabs. 

Tabs would be neat and all, but I think it would be easier and just as effective if we could add a simple entry in mod.json that generates a divider with a title inside of it, e.g.: `----- Section 1 -----`.

Let me know what you think.

**Comment by olegbl** [comment]
Fixed in 020e1a59578c4acc17255a7b5e842a333312bd16
