### ISSUE TITLE
Feature Request: mod name title in mod settings

### ISSUE THREAD

**Issue by Caedendi** [olegbl/d2rmm#9]
When the settings menu for a mod is opened, you currently have no indication which mod's settings menu you are looking at. I think it would be neat if the mod's name could be shown on top as some sort of title to the settings menu.

I'd personally go for either a big `[Mod Name]: settings` or a big `[Mod Name]` with `Settings` on a separate line, but just the mod name would be fine too.

**Comment by olegbl** [comment]
Fixed in 8e8bc44e5f596892d2c644fbdca12333dfb6cde6
